project:
  name: User Balance Microservice
  debug: true
  environment: development

logger:
  level: trace

server:
  host: 0.0.0.0
  port: 7000
  basePath: /balance-service

db:
  DSN: "postgres://user:password@postgres-db:5432/postgres"
  maxOpenConns: 2
  maxIdleConns: 2
  connMaxIdleTime: 5m
  connMaxLifetime: 10m