version: "3.5"

services:
  postgres-db:
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    image: postgres:14.3-alpine

  service:
    build: .
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - '7000:7000'