POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": 1234
}

###

POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": -1
}

###

GET http://localhost:7000/balance-service/accounts/ffa39862-f4ce-4bb1-8f30-ec1aae86c41b
Accept: application/json

###

PUT http://localhost:7000/balance-service/accounts/ffa39862-f4ce-4bb1-8f30-ec1aae86c41b
Accept: application/json

{
  "amount": -114564564456
}

###

POST http://localhost:7000/balance-service/reservations
Content-Type: application/json

{
  "user_id": "497540a7-4d96-41da-9c6b-7a2ad3daa998",
  "service_id": "497540a7-4d96-41da-9c6b-7a2ad3daa998",
  "order_id": "497540a7-4d96-41da-9c6b-7a2ad3daa998",
  "amount": 1
}
