POST http://localhost:7000/balance-service/users
Content-Type: application/json

{
  "amount": 1000000.99
}

###

POST http://localhost:7000/balance-service/users
Content-Type: application/json

{
  "amount": -1
}

###

GET http://localhost:7000/balance-service/users/ffa39862-f4ce-4bb1-8f30-ec1aae86c41b
Accept: application/json

###

PUT http://localhost:7000/balance-service/users/ffa39862-f4ce-4bb1-8f30-ec1aae86c41b
Accept: application/json

{
  "amount": -114564564456
}

###

POST http://localhost:7000/balance-service/reservations
Content-Type: application/json

{
  "user_id": "135f709f-722b-4f2c-86ce-a590f01b62be",
  "service_id": "c467ec7f-3f9a-4b57-bea0-88d9dbbdcdde",
  "order_id": "a925b4d6-49ee-4182-bbf9-d5a7e2496113",
  "amount": 100
}
