POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": 9999999
}

###

POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": -1
}

###

GET http://localhost:7000/balance-service/accounts/982b96e5-7f14-4860-9cd3-50ac19688790
Accept: application/json

###

PUT http://localhost:7000/balance-service/accounts/withdraw
Accept: application/json

{
  "id": "2c4e6e1a-a376-4db6-85e8-adff5a1a8471",
  "amount": 1
}

###

PUT http://localhost:7000/balance-service/accounts/deposit
Accept: application/json

{
  "id": "2c4e6e1a-a376-4db6-85e8-adff5a1a8471",
  "amount": 0.50
}

###

POST http://localhost:7000/balance-service/reservations
Content-Type: application/json

{
  "user_id": "982b96e5-7f14-4860-9cd3-50ac19688790",
  "service_id": "982b96e5-7f14-4860-9cd3-50ac19688790",
  "order_id": "982b96e5-7f14-4860-9cd3-50ac19688790",
  "amount": 34
}

###

DELETE http://localhost:7000/balance-service/reservations/cancel-reservation/afdbd325-3d6c-4b20-985a-af039ef9adeb
Content-Type: application/json

###

DELETE http://localhost:7000/balance-service/reservations/confirm-reservation/5c0c4cd7-5991-46c7-9785-8b7b86fc284a
Content-Type: application/json


###

POST http://localhost:7000/balance-service/transfers
Content-Type: application/json

{
  "to_id": "d570a8bf-d735-45b2-acdc-6d2c3b737110",
  "from_id": "2c4e6e1a-a376-4db6-85e8-adff5a1a8471",
  "amount": 0.30
}