### Создание аккаунта с заданным балансом
POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": 234.23
}

### Запрос на создание аккаунта с отрицательным балансом
POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": -1
}

### Получение информации об аккаунте по ID
GET http://localhost:7000/balance-service/accounts/e028eda5-ae49-4e8c-a52f-fa5363acf071
Accept: application/json

### Списать деньги с баланса пользователя
PUT http://localhost:7000/balance-service/accounts/withdraw/b567e9d6-025c-4d8f-8615-88f391c9e9be
Content-type: application/json

{
  "amount": 1000000000000
}

### Перевод денег на баланс пользователя
PUT http://localhost:7000/balance-service/accounts/deposit/303371c3-3073-488c-971f-f57a6f5aeb6f
Content-Type: application/json

{
  "amount": 453.50
}

### Перевод между пользователями
POST http://localhost:7000/balance-service/transfers
Content-Type: application/json

{
  "amount": 100,
  "from_id": "10473c75-7cb7-405d-bc23-886fd8564cb6",
  "to_id": "01a223c8-462d-4466-94ab-4f98a7ed4c5f"
}

### Зарезервировать деньги за заказ
POST http://localhost:7000/balance-service/reservations
Content-Type: application/json

{
  "user_id": "6c8e7526-95c6-4822-97f8-168c4d2d2fb9",
  "service_id": "e028eda5-ae49-4e8c-a52f-fa5363acf071",
  "order_id": "521ab429-832d-4bc7-b870-26f491ad0b27",
  "amount": 100
}

### Отмена резервирования, возвращение денег пользователю
DELETE http://localhost:7000/balance-service/reservations/cancel-reservation/a51a02f4-a827-4c11-bbbe-43650296b588

### Подтверждение резервирования, внесение записи в отчёт для бухгалтерии
DELETE http://localhost:7000/balance-service/reservations/confirm-reservation/489d6de8-d280-49bd-a27d-a0645d1c24c1

### Список транзакций пользователя, можно указать ключ для пагинации. Подробнее в swagger или README.
GET http://localhost:7000/balance-service/transfers/reports/4509b5d2-bca1-43be-a5e6-44fc9293de2c?order-by=date&page-id=37c07fc9-7747-487c-aac6-f44cd9536b9c
Accept: application/json

### Отчёт для бухгалтерии за определённый месяц
GET http://localhost:7000/balance-service/reports?month=11
Accept: text/csv
