POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": 234.23
}

###

POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": -1
}

###

GET http://localhost:7000/balance-service/accounts/982b96e5-7f14-4860-9cd3-50ac19688790
Accept: application/json

###

PUT http://localhost:7000/balance-service/accounts/withdraw/696a8d48-5a40-4ec2-803d-1f9bd6fb2949
Content-type: application/json

{
  "amount": 1000000000
}

###

PUT http://localhost:7000/balance-service/accounts/deposit/696a8d48-5a40-4ec2-803d-1f9bd6fb2949
Content-Type: application/json

{
  "amount": 453
}

###

POST http://localhost:7000/balance-service/reservations
Content-Type: application/json

{
  "user_id": "9187fb8a-225f-40a9-bcc4-f91a79c32135",
  "service_id": "9187fb8a-225f-40a9-bcc4-f91a79c32135",
  "order_id": "696a8d48-5a40-4ec2-803d-1f9bd6fb2949",
  "amount": 100
}

###

DELETE http://localhost:7000/balance-service/reservations/cancel-reservation/eeafa29f-d963-44b3-b4b3-1432d69ff6b5

###

DELETE http://localhost:7000/balance-service/reservations/confirm-reservation/e6c73f1a-9cbc-4fcb-9227-b47d89519d0d

###

GET http://localhost:7000/balance-service/transfers/reports/696a8d48-5a40-4ec2-803d-1f9bd6fb2949?order-by=amount
Accept: application/json

###

GET http://localhost:7000/balance-service/reports?month=11
Accept: text/csv
