POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": 234.23
}

###

POST http://localhost:7000/balance-service/accounts
Content-Type: application/json

{
  "amount": -1
}

###

GET http://localhost:7000/balance-service/accounts/982b96e5-7f14-4860-9cd3-50ac19688790
Accept: application/json

###

PUT http://localhost:7000/balance-service/accounts/withdraw/696a8d48-5a40-4ec2-803d-1f9bd6fb2949
Content-type: application/json

{
  "amount": 1000000
}

###

PUT http://localhost:7000/balance-service/accounts/deposit/696a8d48-5a40-4ec2-803d-1f9bd6fb2949
Content-Type: application/json

{
  "amount": 453
}

###

POST http://localhost:7000/balance-service/reservations
Content-Type: application/json

{
  "user_id": "696a8d48-5a40-4ec2-803d-1f9bd6fb2949",
  "service_id": "982b96e5-7f14-4860-9cd3-50ac19688790",
  "order_id": "982b96e5-7f14-4860-9cd3-50ac19688790",
  "amount": 4
}

###

DELETE http://localhost:7000/balance-service/reservations/cancel-reservation/0602e6cf-ec04-4437-b2d1-4e8d6ae2f343

###

DELETE http://localhost:7000/balance-service/reservations/confirm-reservation/543f04d3-d4d5-4d95-bfb1-2b15bd7292a3

###

GET http://localhost:7000/balance-service/transfers/reports/2c4e6e1a-a376-4db6-85e8-adff5a1a8471?order-by=amount
Accept: application/json
